import bcrypt from 'bcryptjs';
import prisma from '../src/prisma.js';

const ALDO = 'cmt9tl37g0000tv69uzai0b59';
const OCELLY = 'cmt9tmjjv0001tv69f2nwh7zs';

const passwordHash = await bcrypt.hash('123456', 10);

await prisma.user.createMany({
  data: [
    { id: ALDO, name: 'aldo moroseto', email: 'aldomoroseto668@gmail.com', passwordHash, bio: '' },
    { id: OCELLY, name: 'ocelly opacupan', email: 'ocellyopacupan521@gmail.com', passwordHash, bio: '' },
  ],
});

const recipes = [
  {
    id: 'rec-nasi-goreng-001', authorId: OCELLY, title: 'Nasi Goreng Spesial',
    description: 'Nasi goreng khas Indonesia dengan bumbu rempah pilihan, telur mata sapi, dan ayam goreng renyah. Cocok untuk sarapan atau makan malam.',
    coverUrl: 'https://images.pexels.com/photos/37073151/pexels-photo-37073151.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'EASY', prepTime: 10, cookTime: 15, servings: 2,
    ingredients: [
      { amount: '3', unit: 'piring', name: 'nasi putih' },
      { amount: '2', unit: 'butir', name: 'telur' },
      { amount: '100', unit: 'gram', name: 'ayam goreng' },
      { amount: '3', unit: 'siung', name: 'bawang putih' },
      { amount: '2', unit: 'butir', name: 'bawang merah' },
      { amount: '2', unit: 'buah', name: 'cabe merah' },
      { amount: '1', unit: 'sdm', name: 'kecap manis' },
      { amount: '1', unit: 'sdm', name: 'saus tiram' },
      { amount: '1', unit: 'sdm', name: 'minyak goreng' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: 'secukupnya', unit: '', name: 'merica' },
    ],
    steps: [
      'Tumis bawang putih, bawang merah, dan cabe merah hingga harum.',
      'Masukkan ayam goreng yang sudah dipotong kecil, aduk rata.',
      'Masukkan nasi putih, aduk dengan bumbu hingga rata.',
      'Tambahkan kecap manis dan saus tiram, aduk kembali.',
      'Buat telur mata sapi di sisi wajan, sajikan di atas nasi goreng.',
      'Taburi dengan irisan mentimun dan kerupuk sebagai pelengkap.',
    ],
  },
  {
    id: 'rec-rendang-002', authorId: OCELLY, title: 'Rendang Daging Sapi',
    description: 'Rendang Padang autentik dengan daging sapi empuk yang dimasak perlahan dalam santan dan rempah-rempah. Hidangan khas Minangkabau yang kaya rasa.',
    coverUrl: 'https://images.pexels.com/photos/37249196/pexels-photo-37249196.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'HARD', prepTime: 30, cookTime: 120, servings: 4,
    ingredients: [
      { amount: '500', unit: 'gram', name: 'daging sapi' },
      { amount: '400', unit: 'ml', name: 'santan kental' },
      { amount: '200', unit: 'ml', name: 'santan cair' },
      { amount: '3', unit: 'lembar', name: 'daun jeruk' },
      { amount: '2', unit: 'lembar', name: 'daun salam' },
      { amount: '1', unit: 'ruas', name: 'lengkuas' },
      { amount: '3', unit: 'siung', name: 'bawang putih' },
      { amount: '5', unit: 'butir', name: 'bawang merah' },
      { amount: '5', unit: 'buah', name: 'cabe merah keriting' },
      { amount: '3', unit: 'buah', name: 'cabe rawit' },
      { amount: '1', unit: 'sdm', name: 'ketumbar' },
      { amount: '1', unit: 'sdt', name: 'jintan' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
    ],
    steps: [
      'Potong daging sapi menjadi kotak-kotak kecil, tiriskan.',
      'Haluskan bumbu: bawang putih, bawang merah, cabe, ketumbar, dan jintan.',
      'Tumis bumbu halus bersama daun jeruk, daun salam, dan lengkuas hingga harum.',
      'Masukkan daging sapi, aduk hingga berubah warna.',
      'Tuang santan cair, masak dengan api kecil sambil sesekali diaduk.',
      'Setelah santan menyusut, tuang santan kental. Masak terus hingga kering dan berminyak.',
      'Aduk perlahan agar rendang tidak gosong. Sajikan dengan nasi putih.',
    ],
  },
  {
    id: 'rec-soto-003', authorId: OCELLY, title: 'Soto Ayam Lamongan',
    description: 'Soto ayam khas Lamongan dengan kuah kuning bening yang gurih, lengkap dengan suwiran ayam, telur rebus, dan perkedel kentang.',
    coverUrl: 'https://images.pexels.com/photos/37067921/pexels-photo-37067921.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'MEDIUM', prepTime: 15, cookTime: 30, servings: 3,
    ingredients: [
      { amount: '500', unit: 'gram', name: 'ayam' },
      { amount: '1', unit: 'liter', name: 'air' },
      { amount: '2', unit: 'butir', name: 'telur rebus' },
      { amount: '2', unit: 'sdm', name: 'minyak goreng' },
      { amount: '4', unit: 'siung', name: 'bawang putih' },
      { amount: '3', unit: 'butir', name: 'bawang merah' },
      { amount: '2', unit: 'cm', name: 'kunyit' },
      { amount: '1', unit: 'cm', name: 'jahe' },
      { amount: '2', unit: 'lembar', name: 'daun jeruk' },
      { amount: '1', unit: 'batang', name: 'serai' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: 'secukupnya', unit: '', name: 'merica' },
      { amount: 'secukupnya', unit: '', name: 'bawang goreng' },
    ],
    steps: [
      'Rebus ayam hingga empuk, angkat dan suwir-suwir. Simpan kaldinya.',
      'Haluskan bawang putih, bawang merah, kunyit, dan jahe.',
      'Tumis bumbu halus bersama daun jeruk dan serai hingga harum.',
      'Tuang kaldu ayam ke dalam tumisan, didihkan.',
      'Tambahkan garam dan merica secukupnya.',
      'Sajikan soto dalam mangkuk dengan suwiran ayam, telur rebus belah dua, dan taburan bawang goreng.',
    ],
  },
  {
    id: 'rec-gado-004', authorId: OCELLY, title: 'Gado-Gado Jakarta',
    description: 'Gado-gado segar dengan berbagai sayuran rebus, tahu, tempe, dan telur rebus yang disiram bumbu kacang kental. Hidangan sehat dan bergizi.',
    coverUrl: 'https://images.pexels.com/photos/31336123/pexels-photo-31336123.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'EASY', prepTime: 20, cookTime: 10, servings: 2,
    ingredients: [
      { amount: '150', unit: 'gram', name: 'kacang panjang' },
      { amount: '100', unit: 'gram', name: 'kol' },
      { amount: '2', unit: 'buah', name: 'tahu goreng' },
      { amount: '2', unit: 'lembar', name: 'tempe goreng' },
      { amount: '2', unit: 'butir', name: 'telur rebus' },
      { amount: '100', unit: 'gram', name: 'kacang tanah goreng' },
      { amount: '2', unit: 'siung', name: 'bawang putih' },
      { amount: '3', unit: 'buah', name: 'cabe merah' },
      { amount: '1', unit: 'sdm', name: 'kecap manis' },
      { amount: '1', unit: 'sdm', name: 'air jeruk limau' },
      { amount: '200', unit: 'ml', name: 'air' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: '1', unit: 'piring', name: 'lontong' },
    ],
    steps: [
      'Rebus kacang panjang dan kol hingga layu, tiriskan. Potong-potong.',
      'Goreng tahu dan tempe hingga kecokelatan, potong kecil-kecil.',
      'Haluskan kacang tanah, bawang putih, cabe, garam, dan air hingga halus.',
      'Tambahkan kecap manis dan air jeruk limau ke bumbu kacang, aduk rata.',
      'Tata sayuran, tahu, tempe, dan telur rebus di piring.',
      'Siram dengan bumbu kacang dan taburi bawang goreng. Sajikan dengan lontong.',
    ],
  },
  {
    id: 'rec-ayam-bakar-005', authorId: OCELLY, title: 'Ayam Bakar Madu',
    description: 'Ayam bakar dengan olesan madu dan bumbu rempah yang caramelized sempurna. Daging ayam empuk dengan kulit yang karamel keemasan.',
    coverUrl: 'https://images.pexels.com/photos/37179941/pexels-photo-37179941.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'MEDIUM', prepTime: 40, cookTime: 25, servings: 3,
    ingredients: [
      { amount: '500', unit: 'gram', name: 'ayam potong' },
      { amount: '3', unit: 'sdm', name: 'madu' },
      { amount: '2', unit: 'sdm', name: 'kecap manis' },
      { amount: '2', unit: 'sdm', name: 'minyak goreng' },
      { amount: '4', unit: 'siung', name: 'bawang putih' },
      { amount: '3', unit: 'butir', name: 'bawang merah' },
      { amount: '1', unit: 'cm', name: 'jahe' },
      { amount: '1', unit: 'cm', name: 'kunyit' },
      { amount: '1', unit: 'sdm', name: 'air jeruk nipis' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: 'secukupnya', unit: '', name: 'merica' },
    ],
    steps: [
      'Cuci bersih ayam, lumuri dengan air jeruk nipis dan garam, diamkan 15 menit.',
      'Haluskan bawang putih, bawang merah, jahe, dan kunyit. Tumis hingga harum.',
      'Campurkan bumbu halus dengan madu, kecap manis, minyak, garam, dan merica.',
      'Lumuri ayam dengan bumbu madu, diamkan minimal 30 menit.',
      'Bakar ayam di atas bara api sambil sesekali diolesi sisa bumbu.',
      'Bakar hingga matang dan kulit mengaramel. Sajikan dengan nasi dan lalapan.',
    ],
  },
  {
    id: 'rec-es-teh-006', authorId: OCELLY, title: 'Es Teh Manis Jeruk',
    description: 'Es teh manis segar dengan perasan jeruk nipis, cocok untuk melepas dahaga di hari yang panas. Rasanya manis dengan sentuhan asam segar.',
    coverUrl: 'https://images.pexels.com/photos/12033560/pexels-photo-12033560.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'DRINK', difficulty: 'EASY', prepTime: 5, cookTime: 5, servings: 1,
    ingredients: [
      { amount: '2', unit: 'sachet', name: 'teh celup' },
      { amount: '250', unit: 'ml', name: 'air panas' },
      { amount: '2', unit: 'sdm', name: 'gula pasir' },
      { amount: '2', unit: 'buah', name: 'jeruk nipis' },
      { amount: '200', unit: 'gram', name: 'es batu' },
      { amount: 'secukupnya', unit: '', name: 'daun mint' },
    ],
    steps: [
      'Seduh teh celup dengan air panas, tambahkan gula pasir, aduk hingga larut. Diamkan hingga dingin.',
      'Peras jeruk nipis ke dalam gelas.',
      'Masukkan es batu ke dalam gelas.',
      'Tuang teh yang sudah dingin ke dalam gelas berisi es batu.',
      'Aduk rata dan hias dengan irisan jeruk nipis dan daun mint.',
    ],
  },
  {
    id: 'rec-jus-alpukat-007', authorId: OCELLY, title: 'Jus Alpukat',
    description: 'Jus alpukat kental dan creamy dengan rasa manis alami. Minuman sehat yang kaya nutrisi dan cocok untuk sarapan atau camilan.',
    coverUrl: 'https://images.pexels.com/photos/6614841/pexels-photo-6614841.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'DRINK', difficulty: 'EASY', prepTime: 5, cookTime: 0, servings: 1,
    ingredients: [
      { amount: '1', unit: 'buah', name: 'alpukat matang' },
      { amount: '200', unit: 'ml', name: 'susu cair' },
      { amount: '2', unit: 'sdm', name: 'gula pasir' },
      { amount: '1', unit: 'sdt', name: 'vanili bubuk' },
      { amount: '200', unit: 'gram', name: 'es batu' },
      { amount: '1', unit: 'sdm', name: 'susu kental manis' },
    ],
    steps: [
      'Belah alpukat, buang biji, kerok dagingnya ke dalam blender.',
      'Tambahkan susu cair, gula pasir, dan vanili bubuk.',
      'Blender hingga halus dan creamy.',
      'Masukkan es batu, blender kembali hingga hancur.',
      'Tuang ke dalam gelas, beri siraman susu kental manis di atasnya.',
    ],
  },
  {
    id: 'rec-matcha-008', authorId: OCELLY, title: 'Matcha Latte',
    description: 'Matcha latte hangat dengan campuran bubuk matcha premium dan susu segar. Minuman khas Jepang yang menenangkan dengan rasa teh hijau autentik.',
    coverUrl: 'https://images.pexels.com/photos/14430999/pexels-photo-14430999.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'DRINK', difficulty: 'EASY', prepTime: 5, cookTime: 5, servings: 1,
    ingredients: [
      { amount: '2', unit: 'sdt', name: 'bubuk matcha' },
      { amount: '60', unit: 'ml', name: 'air panas' },
      { amount: '250', unit: 'ml', name: 'susu segar' },
      { amount: '2', unit: 'sdm', name: 'gula pasir' },
      { amount: 'secukupnya', unit: '', name: 'buih susu' },
    ],
    steps: [
      'Ayak bubuk matcha ke dalam mangkuk kecil.',
      'Tuang air panas (bukan mendidih, sekitar 80 derajat Celsius).',
      'Kocok dengan chasen atau whisk hingga larut dan berbuih.',
      'Panaskan susu hingga suhu hangat, buat buih susu jika ada.',
      'Tuang matcha ke dalam gelas, tambahkan gula pasir.',
      'Tuang susu hangat perlahan ke atas matcha, aduk perlahan.',
    ],
  },
  {
    id: 'rec-martabak-009', authorId: OCELLY, title: 'Martabak Manis',
    description: 'Martabak manis atau terang bulan dengan isian coklat meses dan keju yang lumer. Adonan lembut dengan tekstur berlubang-lubang yang sempurna.',
    coverUrl: 'https://images.pexels.com/photos/37240958/pexels-photo-37240958.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'MEDIUM', prepTime: 15, cookTime: 45, servings: 4,
    ingredients: [
      { amount: '250', unit: 'gram', name: 'tepung terigu' },
      { amount: '1', unit: 'butir', name: 'telur' },
      { amount: '200', unit: 'ml', name: 'susu cair' },
      { amount: '2', unit: 'sdm', name: 'gula pasir' },
      { amount: '1', unit: 'sdt', name: 'ragi instan' },
      { amount: '1', unit: 'sdt', name: 'baking powder' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: '2', unit: 'sdm', name: 'mentega' },
      { amount: '3', unit: 'sdm', name: 'meses coklat' },
      { amount: '50', unit: 'gram', name: 'keju parut' },
      { amount: '2', unit: 'sdm', name: 'kental manis' },
    ],
    steps: [
      'Campur tepung terigu, gula, ragi, baking powder, dan garam dalam mangkuk.',
      'Tambahkan telur dan susu cair, aduk hingga licin. Diamkan 1 jam hingga mengembang.',
      'Panaskan teflon dengan api kecil, tuang adonan ke tengah wajan.',
      'Tutup wajan dan masak hingga permukaan berlubang-lubang dan matang.',
      'Olesi dengan mentega selagi panas.',
      'Taburi meses coklat dan keju parut, siram dengan kental manis.',
      'Lipat dua, potong-potong dan sajikan hangat.',
    ],
  },
  {
    id: 'rec-pisang-goreng-010', authorId: OCELLY, title: 'Pisang Goreng Crispy',
    description: 'Pisang goreng tepung crispy dengan baluran tepung renyah di luar dan lembut di dalam. Camilan tradisional Indonesia yang selalu digemari.',
    coverUrl: 'https://images.pexels.com/photos/37048319/pexels-photo-37048319.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'EASY', prepTime: 10, cookTime: 10, servings: 4,
    ingredients: [
      { amount: '4', unit: 'buah', name: 'pisang raja/pisang kepok' },
      { amount: '150', unit: 'gram', name: 'tepung terigu' },
      { amount: '2', unit: 'sdm', name: 'tepung beras' },
      { amount: '2', unit: 'sdm', name: 'gula pasir' },
      { amount: '1', unit: 'sdt', name: 'vanili bubuk' },
      { amount: '200', unit: 'ml', name: 'air' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: 'secukupnya', unit: '', name: 'minyak goreng' },
    ],
    steps: [
      'Kupas pisang, belah menjadi dua memanjang. Pipihkan sedikit.',
      'Campur tepung terigu, tepung beras, gula pasir, vanili, garam, dan air. Aduk hingga licin.',
      'Panaskan minyak goreng dalam wajan dengan api sedang.',
      'Celupkan pisang ke dalam adonan tepung hingga rata.',
      'Goreng dalam minyak panas hingga keemasan dan crispy.',
      'Angkat dan tiriskan di atas kertas minyak. Sajikan hangat.',
    ],
  },
  {
    id: 'rec-mie-goreng-001', authorId: ALDO, title: 'Mie Goreng Jawa',
    description: 'Mie goreng khas Jawa dengan bumbu kecap manis yang karamelisasi, ditambah sayuran segar dan telur orak-arik. Hidangan mie favorit sepanjang masa.',
    coverUrl: 'https://images.pexels.com/photos/37105809/pexels-photo-37105809.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'EASY', prepTime: 10, cookTime: 15, servings: 2,
    ingredients: [
      { amount: '250', unit: 'gram', name: 'mie kuning' },
      { amount: '2', unit: 'butir', name: 'telur' },
      { amount: '100', unit: 'gram', name: 'sawi hijau' },
      { amount: '100', unit: 'gram', name: 'kol' },
      { amount: '2', unit: 'siung', name: 'bawang putih' },
      { amount: '2', unit: 'butir', name: 'bawang merah' },
      { amount: '3', unit: 'sdm', name: 'kecap manis' },
      { amount: '1', unit: 'sdm', name: 'saus tiram' },
      { amount: '1', unit: 'sdm', name: 'minyak goreng' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: 'secukupnya', unit: '', name: 'merica' },
    ],
    steps: [
      'Rebus mie kuning hingga setengah matang, tiriskan.',
      'Tumis bawang putih dan bawang merah hingga harum.',
      'Masukkan telur, orak-arik hingga matang.',
      'Tambahkan sayuran (sawi dan kol), aduk hingga layu.',
      'Masukkan mie, kecap manis, saus tiram, garam, dan merica. Aduk rata dengan api besar.',
      'Sajikan dengan irisan mentimun dan kerupuk.',
    ],
  },
  {
    id: 'rec-sate-002', authorId: ALDO, title: 'Sate Ayam Madura',
    description: 'Sate ayam Madura dengan bumbu kacang kental manis dan gurih. Tusuk ayam bakar bumbu kecap yang juicy dengan aroma arang yang khas.',
    coverUrl: 'https://images.pexels.com/photos/37076559/pexels-photo-37076559.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'MEDIUM', prepTime: 40, cookTime: 15, servings: 3,
    ingredients: [
      { amount: '500', unit: 'gram', name: 'dada ayam' },
      { amount: '3', unit: 'sdm', name: 'kecap manis' },
      { amount: '2', unit: 'sdm', name: 'minyak goreng' },
      { amount: '100', unit: 'gram', name: 'kacang tanah goreng' },
      { amount: '2', unit: 'siung', name: 'bawang putih' },
      { amount: '3', unit: 'buah', name: 'cabe merah' },
      { amount: '1', unit: 'sdm', name: 'gula merah' },
      { amount: '100', unit: 'ml', name: 'air' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: '1', unit: 'batang', name: 'serai' },
    ],
    steps: [
      'Potong ayam dadu kecil-kecil, tusuk-tusuk dengan tusuk sate.',
      'Lumuri tusuk sate dengan kecap manis dan minyak goreng. Diamkan 30 menit.',
      'Haluskan kacang tanah, bawang putih, cabe, gula merah, dan garam. Tambahkan air, aduk hingga kental.',
      'Bakar sate di atas bara api sambil sesekali diolesi bumbu kacang.',
      'Bakar hingga matang kecokelatan di bagian pinggirnya.',
      'Sajikan sate dengan bumbu kacang, irisan bawang merah, dan lontong.',
    ],
  },
  {
    id: 'rec-bakso-003', authorId: ALDO, title: 'Bakso Malang',
    description: 'Bakso Malang komplit dengan berbagai jenis bakso, mie, siomay, dan pangsit goreng dalam kuah kaldu sapi yang gurih dan nikmat.',
    coverUrl: 'https://images.pexels.com/photos/37105766/pexels-photo-37105766.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'MEDIUM', prepTime: 15, cookTime: 30, servings: 3,
    ingredients: [
      { amount: '300', unit: 'gram', name: 'bakso sapi' },
      { amount: '200', unit: 'gram', name: 'siomay' },
      { amount: '100', unit: 'gram', name: 'mie kuning' },
      { amount: '100', unit: 'gram', name: 'bihun' },
      { amount: '1', unit: 'liter', name: 'kaldu sapi' },
      { amount: '2', unit: 'siung', name: 'bawang putih' },
      { amount: '1', unit: 'cm', name: 'jahe' },
      { amount: '2', unit: 'lembar', name: 'daun bawang' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: 'secukupnya', unit: '', name: 'merica' },
      { amount: 'secukupnya', unit: '', name: 'bawang goreng' },
      { amount: '2', unit: 'batang', name: 'seledri' },
    ],
    steps: [
      'Didihkan kaldu sapi dengan bawang putih, jahe, garam, dan merica.',
      'Masukkan bakso sapi dan siomay ke dalam kuah mendidih. Masak hingga mengapung.',
      'Rebus mie kuning dan bihun hingga matang, tiriskan.',
      'Tata mie dan bihun dalam mangkuk, tambahkan bakso dan siomay.',
      'Siram dengan kuah panas, taburi bawang goreng dan irisan seledri.',
      'Sajikan dengan sambal dan kecap sesuai selera.',
    ],
  },
  {
    id: 'rec-nasi-uduk-004', authorId: ALDO, title: 'Nasi Uduk Betawi',
    description: 'Nasi uduk khas Betawi yang dimasak dengan santan dan rempah-rempah. Nasi putih yang harum, gurih, dan lembut dengan aroma daun jeruk yang khas.',
    coverUrl: 'https://images.pexels.com/photos/37134616/pexels-photo-37134616.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'EASY', prepTime: 15, cookTime: 30, servings: 4,
    ingredients: [
      { amount: '400', unit: 'gram', name: 'beras putih' },
      { amount: '400', unit: 'ml', name: 'santan' },
      { amount: '2', unit: 'lembar', name: 'daun jeruk' },
      { amount: '1', unit: 'lembar', name: 'daun salam' },
      { amount: '1', unit: 'batang', name: 'serai' },
      { amount: '2', unit: 'cm', name: 'lengkuas' },
      { amount: '3', unit: 'butir', name: 'bawang merah' },
      { amount: '2', unit: 'siung', name: 'bawang putih' },
      { amount: '1', unit: 'sdt', name: 'ketumbar bubuk' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: '1', unit: 'sdm', name: 'mentega' },
    ],
    steps: [
      'Cuci beras hingga bersih, tiriskan.',
      'Tumis bawang merah, bawang putih, dan ketumbar hingga harum.',
      'Masukkan beras ke dalam rice cooker, tambahkan tumisan bumbu.',
      'Tuang santan, tambahkan daun jeruk, daun salam, serai, lengkuas, dan garam.',
      'Aduk rata, masak hingga nasi matang dan pulen.',
      'Sajikan nasi uduk dengan lauk pelengkap: ayam goreng, tempe, tahu, dan sambal.',
    ],
  },
  {
    id: 'rec-pempek-005', authorId: ALDO, title: 'Pempek Palembang',
    description: 'Pempek ikan tenggiri khas Palembang dengan tekstur kenyal dan gurih, disiram kuah cuko yang asam manis pedas. Hidangan laut legendaris Sumatera.',
    coverUrl: 'https://images.pexels.com/photos/8732583/pexels-photo-8732583.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'HARD', prepTime: 45, cookTime: 20, servings: 4,
    ingredients: [
      { amount: '500', unit: 'gram', name: 'ikan tenggiri giling' },
      { amount: '200', unit: 'gram', name: 'tepung tapioka' },
      { amount: '1', unit: 'butir', name: 'telur' },
      { amount: '200', unit: 'ml', name: 'air es' },
      { amount: '1', unit: 'sdt', name: 'garam' },
      { amount: '1', unit: 'sdt', name: 'merica' },
      { amount: '4', unit: 'siung', name: 'bawang putih' },
      { amount: '100', unit: 'gram', name: 'gula merah' },
      { amount: '200', unit: 'ml', name: 'air cuko' },
      { amount: '3', unit: 'buah', name: 'cabe rawit' },
      { amount: '2', unit: 'sdm', name: 'cuka' },
    ],
    steps: [
      'Campur ikan tenggiri giling dengan air es, aduk hingga lengket.',
      'Tambahkan telur, garam, merica, dan bawang putih halus. Aduk rata.',
      'Masukkan tepung sedikit demi sedikit, uleni hingga adonan bisa dibentuk.',
      'Bentuk adonan menjadi bulat pipih (kapal selam) atau bentuk sesuai selera.',
      'Rebus pempek dalam air mendidih hingga mengapung, angkat dan tiriskan.',
      'Goreng pempek hingga kecokelatan. Sajikan dengan kuah cuko.',
    ],
  },
  {
    id: 'rec-es-campur-006', authorId: ALDO, title: 'Es Campur',
    description: 'Es campur segar dengan berbagai isian buah, cincau, dan kolang-kaling dalam kuah santan yang manis. Minuman pelepas dahaga favorit semua kalangan.',
    coverUrl: 'https://images.pexels.com/photos/37107008/pexels-photo-37107008.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'DRINK', difficulty: 'EASY', prepTime: 15, cookTime: 10, servings: 2,
    ingredients: [
      { amount: '200', unit: 'ml', name: 'santan' },
      { amount: '2', unit: 'sdm', name: 'gula pasir' },
      { amount: '1', unit: 'buah', name: 'alpukat' },
      { amount: '100', unit: 'gram', name: 'kolang-kaling' },
      { amount: '100', unit: 'gram', name: 'cincau hitam' },
      { amount: '50', unit: 'gram', name: 'nata de coco' },
      { amount: '1', unit: 'sdm', name: 'sirup merah' },
      { amount: '200', unit: 'gram', name: 'es batu' },
      { amount: '1', unit: 'sdt', name: 'vanili bubuk' },
    ],
    steps: [
      'Rebus kolang-kaling dengan sedikit gula hingga empuk, tiriskan.',
      'Potong cincau dan nata de coco menjadi potongan kecil-kecil.',
      'Kerok alpukat menjadi irisan tipis.',
      'Campur santan, gula pasir, dan vanili bubuk, aduk hingga larut.',
      'Masukkan es batu ke dalam gelas, tata semua isian di atasnya.',
      'Siram dengan kuah santan dan tetesi sirup merah. Sajikan segera.',
    ],
  },
  {
    id: 'rec-wedang-jahe-007', authorId: ALDO, title: 'Wedang Jahe',
    description: 'Wedang jahe hangat dengan rasa pedas alami jahe segar dan manis gula merah. Minuman tradisional Jawa yang menghangatkan tubuh dan menyehatkan.',
    coverUrl: 'https://images.pexels.com/photos/6427781/pexels-photo-6427781.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'DRINK', difficulty: 'EASY', prepTime: 5, cookTime: 15, servings: 2,
    ingredients: [
      { amount: '50', unit: 'gram', name: 'jahe segar' },
      { amount: '200', unit: 'gram', name: 'gula merah' },
      { amount: '500', unit: 'ml', name: 'air' },
      { amount: '2', unit: 'lembar', name: 'daun pandan' },
      { amount: '1', unit: 'batang', name: 'sereh' },
      { amount: '3', unit: 'butir', name: 'cengkeh' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
    ],
    steps: [
      'Bakar jahe sebentar hingga kulit agak hangus, memarkan.',
      'Masak air bersama jahe, sereh, cengkeh, dan daun pandan hingga mendidih.',
      'Masukkan gula merah dan sejumput garam, aduk hingga larut.',
      'Kecilkan api, biarkan mendidih perlahan selama 10 menit.',
      'Saring wedang ke dalam cangkir, sajikan hangat-hangat.',
    ],
  },
  {
    id: 'rec-cendol-008', authorId: ALDO, title: 'Es Cendol Dawet',
    description: 'Es cendol dawet tradisional dengan cincau hijau, santan gurih, dan gula merah. Minuman khas Jawa yang menyegarkan dengan tekstur cendol yang kenyal.',
    coverUrl: 'https://images.pexels.com/photos/37106997/pexels-photo-37106997.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'DRINK', difficulty: 'EASY', prepTime: 10, cookTime: 15, servings: 2,
    ingredients: [
      { amount: '200', unit: 'ml', name: 'santan' },
      { amount: '150', unit: 'gram', name: 'gula merah' },
      { amount: '200', unit: 'ml', name: 'air' },
      { amount: '100', unit: 'gram', name: 'cendol hijau' },
      { amount: '100', unit: 'gram', name: 'cincau' },
      { amount: '200', unit: 'gram', name: 'es batu' },
      { amount: '1', unit: 'lembar', name: 'daun pandan' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
    ],
    steps: [
      'Masak gula merah dengan air dan daun pandan hingga larut, saring. Sisihkan.',
      'Masak santan dengan sejumput garam hingga mendidih, angkat. Sisihkan.',
      'Siapkan gelas, masukkan cendol dan cincau.',
      'Tambahkan es batu secukupnya.',
      'Tuang santan dan sirup gula merah. Aduk perlahan sebelum diminum.',
    ],
  },
  {
    id: 'rec-kue-lapis-009', authorId: ALDO, title: 'Kue Lapis',
    description: 'Kue lapis pelangi yang lembut dan manis dengan lapisan warna-warni. Kue tradisional Indonesia yang cantik dan cocok untuk jamuan atau camilan.',
    coverUrl: 'https://images.pexels.com/photos/31336127/pexels-photo-31336127.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'MEDIUM', prepTime: 20, cookTime: 60, servings: 8,
    ingredients: [
      { amount: '250', unit: 'gram', name: 'tepung beras' },
      { amount: '50', unit: 'gram', name: 'tepung tapioka' },
      { amount: '400', unit: 'ml', name: 'santan' },
      { amount: '200', unit: 'gram', name: 'gula pasir' },
      { amount: '1', unit: 'sdt', name: 'vanili bubuk' },
      { amount: 'secukupnya', unit: '', name: 'pewarna makanan' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
    ],
    steps: [
      'Campur tepung beras, tepung tapioka, gula, dan garam dalam mangkuk besar.',
      'Tuang santan sedikit demi sedikit sambil diaduk hingga licin dan tidak menggumpal.',
      'Bagi adonan menjadi beberapa bagian berdasarkan jumlah pewarna.',
      'Tambahkan pewarna berbeda ke masing-masing bagian adonan.',
      'Tuang adonan lapisan pertama ke dalam loyang, kukus hingga matang.',
      'Tuang lapisan berikutnya bergantian, kukus masing-masing hingga matang sebelum menambahkan lapisan baru.',
      'Setelah semua lapisan matang, dinginkan kue sebelum dipotong.',
    ],
  },
  {
    id: 'rec-tempe-goreng-010', authorId: ALDO, title: 'Tempe Goreng Tepung',
    description: 'Tempe goreng tepung renyah di luar dan lembut di dalam, dibumbui bawang putih dan ketumbar. Camilan sehat kaya protein yang disukai semua orang.',
    coverUrl: 'https://images.pexels.com/photos/37079586/pexels-photo-37079586.jpeg?auto=compress&cs=tinysrgb&w=800',
    category: 'FOOD', difficulty: 'EASY', prepTime: 10, cookTime: 10, servings: 3,
    ingredients: [
      { amount: '300', unit: 'gram', name: 'tempe' },
      { amount: '150', unit: 'gram', name: 'tepung terigu' },
      { amount: '50', unit: 'gram', name: 'tepung beras' },
      { amount: '3', unit: 'siung', name: 'bawang putih' },
      { amount: '1', unit: 'sdt', name: 'ketumbar bubuk' },
      { amount: '1', unit: 'sdt', name: 'merica' },
      { amount: '200', unit: 'ml', name: 'air' },
      { amount: 'secukupnya', unit: '', name: 'garam' },
      { amount: 'secukupnya', unit: '', name: 'minyak goreng' },
    ],
    steps: [
      'Potong tempe menjadi irisan tipis memanjang atau kotak-kotak.',
      'Haluskan bawang putih, garam, ketumbar, dan merica.',
      'Campur tepung terigu, tepung beras, dan bumbu halus. Tambahkan air, aduk hingga adonan kental.',
      'Celupkan tempe ke dalam adonan tepung hingga rata.',
      'Goreng dalam minyak panas hingga keemasan dan crispy.',
      'Angkat, tiriskan di atas kertas minyak. Sajikan dengan cabai rawit.',
    ],
  },
];

for (const r of recipes) {
  await prisma.recipe.create({
    data: {
      id: r.id,
      authorId: r.authorId,
      title: r.title,
      description: r.description,
      coverUrl: r.coverUrl,
      category: r.category,
      difficulty: r.difficulty,
      prepTime: r.prepTime,
      cookTime: r.cookTime,
      servings: r.servings,
      ingredients: r.ingredients,
      steps: r.steps,
      visibility: 'PUBLIC',
    },
  });
}

const count = await prisma.recipe.count();
console.log(`Seed selesai: ${count} resep`);
await prisma.$disconnect();