import {
  Coffee, Wine, Clock, Timer, Play, Pause, RotateCcw,
  ClipboardList, ListOrdered, Lock, Unlock, Globe,
  Bookmark, MessageSquare, Heart, User, Users,
  Send, Share2, ShoppingCart, Copy, Trash2,
  TriangleAlert, Search, Eye, EyeOff, BookOpen,
  CircleAlert, Check, ChevronLeft, X, Home,
  Settings, LogOut, Bell, Plus, Star,
  Sprout, Flame, Pencil, Info, Grid3X3,
  Camera, Menu, ArrowRight, Reply, Download,
  Trophy, CookingPot,
} from 'lucide-react';

const ICONS = {
  food: Coffee,
  drink: Wine,
  clock: Clock,
  timer: Timer,
  play: Play,
  pause: Pause,
  reset: RotateCcw,
  ingredients: ClipboardList,
  steps: ListOrdered,
  lock: Lock,
  unlock: Unlock,
  globe: Globe,
  bookmark: Bookmark,
  'bookmark-filled': Bookmark,
  chat: MessageSquare,
  heart: Heart,
  'heart-filled': Heart,
  user: User,
  users: Users,
  send: Send,
  share: Share2,
  cart: ShoppingCart,
  copy: Copy,
  trash: Trash2,
  warning: TriangleAlert,
  search: Search,
  eye: Eye,
  'eye-off': EyeOff,
  book: BookOpen,
  'alert-circle': CircleAlert,
  check: Check,
  'chevron-left': ChevronLeft,
  x: X,
  home: Home,
  settings: Settings,
  logout: LogOut,
  bell: Bell,
  plus: Plus,
  star: Star,
  'star-filled': Star,
  seedling: Sprout,
  flame: Flame,
  fire: Flame,
  write: Pencil,
  info: Info,
  grip: Grid3X3,
  camera: Camera,
  menu: Menu,
  'arrow-right': ArrowRight,
  reply: Reply,
  download: Download,
  trophy: Trophy,
  'cooking-pot': CookingPot,
};

const FILLED_ICONS = new Set(['bookmark-filled', 'heart-filled', 'star-filled']);

export default function Icon({ name, className = 'h-5 w-5' }) {
  const Component = ICONS[name];
  if (!Component) return null;
  return <Component className={className} fill={FILLED_ICONS.has(name) ? 'currentColor' : 'none'} />;
}
